POST http://localhost:8000/user/login
content-type: application/json

{
    "username": "changarea",
    "password": "tlRKeZuwOb3DrIq"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "username": "Test",
    "password": "testpass123"
}